package sbnz.integracija;

import sbz.cardiagnosticbe.model.drools.VisibleSymptoms;
import sbz.cardiagnosticbe.model.drools.FailureList;
import sbz.cardiagnosticbe.model.Failure;
import sbz.cardiagnosticbe.model.Symptom;

import java.util.Set;
import java.util.List;

rule "Detect failures"
    agenda-group "detect-failure"
    when
        $result: FailureList();
        $s: VisibleSymptoms($visibleSymptoms: symptoms, $userCarState: carState);
        $f: Failure($failureSymptoms: symptoms, carState == $userCarState)
        $visibleIndicatorsIds: Set() from accumulate (
            Symptom($id: id) from $visibleSymptoms, collectSet($id)
        )
        checkFailureSymptoms($failureSymptoms, $visibleIndicatorsIds;);
    then
        $result.getFailures().add($f);
end

query checkFailureSymptoms(Set failureSymptoms, List visibleSymptomsIds)
    $cnt: Number(intValue == failureSymptoms.size()) from accumulate(
        Symptom($id: id, id memberOf visibleSymptomsIds) from failureSymptoms,
        init(int num = 0;),
        action(num += 1;),
        result(num)
    )
end
