package sbnz.integracija;

import sbz.cardiagnosticbe.dto.failure.TFailure;
import sbz.cardiagnosticbe.model.enums.VehiclePart;

rule "Adding failure - formating DTC code 1"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.POWERTRAIN, isManufacturerSpecific == false)
    then
        String dtcCode = "P0" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  2"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.BODY && isManufacturerSpecific == false)
    then
        String dtcCode = "B0" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  3"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.NETWORK_VEHICLE_INTEGRATION && isManufacturerSpecific == false)
    then
        String dtcCode = "U0" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  4"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.CHASIS && isManufacturerSpecific == false)
    then
        String dtcCode = "C0" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  5"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.POWERTRAIN && isManufacturerSpecific == true)
    then
        String dtcCode = "P1" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  6"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.BODY && isManufacturerSpecific == true)
    then
        String dtcCode = "B1" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  7"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.NETWORK_VEHICLE_INTEGRATION && isManufacturerSpecific == true)
    then
        String dtcCode = "U1" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

rule "Adding failure - formating DTC code  8"
    agenda-group "add-failure"
    when
        $f: TFailure(vehiclePart == VehiclePart.CHASIS && isManufacturerSpecific == true)
    then
        String dtcCode = "C1" + $f.getVehicleSubsystem();
        $f.setDtcCode(dtcCode);
end

