package sbnz.integracija;

import sbz.cardiagnosticbe.dto.TDtcParams;
import sbz.cardiagnosticbe.model.enums.VehiclePart;
import sbz.cardiagnosticbe.model.drools.Dtc;

rule "Filtering failure by DTC - formating DTC code  1"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.POWERTRAIN && isManufacturerSpecific == false)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("P0" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 2"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.BODY && isManufacturerSpecific == false)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("B0" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 3"
    agenda-group "failure-by-dtce"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.NETWORK_VEHICLE_INTEGRATION && isManufacturerSpecific == false)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("U0" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 4"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.CHASIS && isManufacturerSpecific == false)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("C0" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 5"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.POWERTRAIN && isManufacturerSpecific == true)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("P1" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 6"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.BODY && isManufacturerSpecific == true)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("B1" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 7"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.NETWORK_VEHICLE_INTEGRATION && isManufacturerSpecific == true)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("U1" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end

rule "Filtering failure by DTC - formating DTC code 8"
    agenda-group "failure-by-dtc"
    when
        $f: TDtcParams(vehiclePart == VehiclePart.CHASIS && isManufacturerSpecific == true)
    then
        Dtc dtc = new Dtc();
        dtc.setDtc("C1" + $f.getVehicleSubsystem());
        System.out.println(dtc.getDtc());
        insert(dtc);
end
