package sbz.cardiagnosticbe.model.enums;

public enum VehicleSubsystem {
    FUEL_AND_AIR_METERING_AND_AUXILIARY_EMISSION_CONTROLS,
    FUEL_AND_AIR_METERING,
    FUEL_AND_AIR_METERING_INJECTOR_CIRCUIT,
    IGNITION_SYSTEMS_OR_MISFIRES,
    AUXILIARY_EMISSION_CONTROLS,
    VEHICLE_SPEED_CONTROL_IDLE_CONTROL_SYSTEMS_AND_AUXILIARY_INPUTS,
    COMPUTER_AND_OUTPUT_CIRCUIT,
    TRANSMISSION
}
